theme = "catppuccin_frappe"

[editor]
cursorline = true
auto-save = true
bufferline = "always"
color-modes = true
completion-trigger-len = 1
rulers = [80, 120]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = [":buffer-next"]
"S-tab" = [":buffer-previous"]
X = ["extend_line_up"]
L = ["goto_line_end"]
H = ["goto_line_start"]
J = ["move_visual_line_down","move_visual_line_down","move_visual_line_down"]
K = ["move_visual_line_up","move_visual_line_up","move_visual_line_up"]
D = ["kill_to_line_end"]
C = ["kill_to_line_end", "insert_mode"]
V = ["copy_selection_on_next_line"]
A-m = "select_next_sibling"
A-n = "select_prev_sibling"

[keys.select]
L = ["goto_line_end"]
H = ["goto_line_start"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 20

[editor.statusline]
center = ["version-control"]
right = [
  "diagnostics",
  "primary-selection-length",
  "selections",
  "register",
  "position",
  "file-encoding",
  "file-line-ending",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true 

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

# https://quantonganh.com/2023/08/19/turn-helix-into-ide 
[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
R = ["change_selection", "paste_clipboard_before", "normal_mode"]
X = ":buffer-close-others"
C-q = ":quit-all"
C-s = ":write!"
x = ":buffer-close"

# g = ":pipe-to wezterm cli split-pane -- helix-live-grep"
# l = ":pipe-to helix-debug-print"
# g = [":pipe-to wezterm cli split-pane --cwd $(pwd) -- helix-live-grep"]
# g = [":pipe-to zellij run -f -c -- helix-live-grep"]
# e = [":pipe-to wezterm cli split-pane --percent 80 -- helix-nnn-pick-current"]
# t = [":pipe-to wezterm cli split-pane --percent 80 -- helix-fzf"]
# e = [":pipe-to wezterm cli split-pane --cwd $(pwd) -- helix-lf-pick-current"]
# space = [":new", ":insert-output lf-pick", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":redraw"]

# B = ":pipe-to wezterm cli split-pane -- hx-git-blame"

space = [":new", ":insert-output lf-pick-current", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":redraw"]

[keys.normal.";"]
b = ":sh hx-wezterm.sh blame"
e = ":sh hx-wezterm.sh explorer"
f = ":sh hx-wezterm.sh file-search"
F = ":sh hx-wezterm.sh file-grep"
g = ":sh hx-wezterm.sh lazygit"
