theme = "catppuccin_frappe"

[editor]
cursorline = true
auto-save = true
bufferline = "always"
color-modes = true
completion-trigger-len = 1

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = [":buffer-next"]
"S-tab" = [":buffer-previous"]
X = ["extend_line_up"]
L = ["goto_line_end"]
H = ["goto_line_start"]
A-f = [":theme catppuccin_frappe"]
C-f = [":new", ":insert-output lf-pick", "split_selection_on_newline", "goto_file", "goto_last_modification", "goto_last_modified_file", ":buffer-close!", ":theme default"]

[keys.select]
L = ["goto_line_end"]
H = ["goto_line_start"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 20

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true 

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
# g = ":pipe-to wezterm cli split-pane -- helix-live-grep"
# l = ":pipe-to helix-debug-print"
x = ":buffer-close"
X = ":buffer-close-others"
C-q = ":quit-all"
C-s = ":write-all"
G = [":pipe-to wezterm cli split-pane -- helix-live-grep"]
