# Sets user-defined palette
palette = "catppuccin_mocha"

add_newline = true
scan_timeout = 10

format = """
$hostname$directory$git_branch$git_status
$username$shell$character"""

[line_break]
disabled = true

[character]
success_symbol = "[❯](yellow)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

# [fill]
# symbol = " "
# style = "fg:yellow bg:peach"
# #
[cmd_duration]
format = "[$duration]($style)"
style = 'bright-black'
#
[time]
format = '[\[$time\] ](fg:#fff1cf bg:themebg)'
utc_time_offset = "local"
time_format = "%T"
disabled = false
time_range = "-"
#


[hostname]
ssh_only = false
disabled = false
format = "[](fg:hostnametext bold)[$hostname](bg:hostnametext fg:themebg bold)[](fg:hostnametext bg:dirtext)"

[directory]
format = "[$path]($style)[$read_only](bg:dirtext fg:themebg bold)[ ](fg:dirtext bold bg:gittext)"
style = "bg:dirtext fg:themebg bold"
truncation_symbol = "…/"
truncate_to_repo = false
truncation_length = 100
home_symbol = " "

[git_branch]
format = "[$symbol$branch](fg:bold themebg bg:gittext)[](fg:gittext)"
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]](fg:#fff1cf bg:themebg)[ ](fg:#fff1cf bg:themebg))'

[username]
format = "[](fg:usertext bold)[$user](fg:themebg bg:usertext bold)[ ](fg:usertext bg:themebg bold)"
show_always = true
disabled = false

[shell]
zsh_indicator = "[](fg:zshbg bg:themebg)[ZSH](fg:zshtext bg:zshbg)[](fg:zshbg bg:themebg)(fg:themebg)"
bash_indicator = "[](fg:#c4c431 bg:themebg)[BSH](fg:#fff1cf bg:#c4c431)[](fg:#c4c431 bg:themebg)[  ](fg:#c4c431 bg:themebg)[](fg:themebg)"
nu_indicator = "[](fg:#fe6142 bg:themebg)[NSH](fg:#fff1cf bg:#fe6142)[](fg:#fe6142 bg:themebg)[  ](fg:#fe6142 bg:themebg)[](fg:themebg)"
fish_indicator = "[](fg:#5442f5 bg:themebg)[FSH](fg:#fff1cf bg:#5442f5)[](fg:#5442f5 bg:themebg)[  ](fg:#5442f5 bg:themebg)[](fg:themebg)"
elvish_indicator = "[](fg:#a742f5 bg:themebg)[ESH](fg:#fff1cf bg:#a742f5)[](fg:#a742f5 bg:themebg)[  ](fg:#a742f5 bg:themebg)[](fg:themebg)"
xonsh_indicator = "[](fg:#70ff24 bg:themebg)[XSH](fg:#fff1cf bg:#70ff24)[](fg:#70ff24 bg:themebg)[  ](fg:#70ff24 bg:themebg)[](fg:themebg)"
unknown_indicator = "[](fg:#fff1cf bg:themebg)[?MODE][](fg:themebg)"
style = "fg:#fff1cf bg:themebg"
disabled = false



[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

themebg = "#11111b"

dirtext = "#f9e2af"
gittext = "#eba0ac"

hostnametext = "#89dceb"
usertext = "#94e2d5"

zshtext = "#89dceb"
zshbg = "#313244"


